### ISSUE TITLE
Recognize name of current module

### ISSUE THREAD

**Issue by Lysxia** [whonore/Coqtail#144]
A file `A.v` can refer to its own contents by prefixing it with its own name:

```
(* A.v *)
Definition x := 0.
Print A.x.  (* coqc accepts this *)
```

Coqtail currently rejects that.

**Comment by whonore** [comment]
The problem seems to be that `coqc` sets the toplevel module name to the file name, while `coqidetop` sets it to `Top`. This can be overridden with the `-top` or `-topfile` arguments, which I think is what `coqide` does.

A temporary workaround is to pass one of these arguments manually (`:CoqStart -top A`).

**Comment by Lysxia** [comment]
Thanks!
