### ISSUE TITLE
Update tag stack on CoqGotoDef

### ISSUE THREAD

**Issue by j-hui** [whonore/Coqtail#174]
This is done natively when Vim/Neovim has `tagfunc` available, but `tagfunc` is not available on Vim <8.1 or on Neovim 0.4.4 (current stable). It will still take a bit of time until this is widely available.

While it's possible to use the quickfix/jump list, this feature is still nice to have for those used to `<C-t>`. For instance, it's available/configurable on [vim-lsp](https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/utils/tagstack.vim) and [ALE](https://github.com/dense-analysis/ale/blob/master/autoload/ale/definition.vim#L24).

Note that `{get,set}tagstack()` aren't always available either, but they are at least provided by Neovim where `tagfunc` is not.

**Comment by whonore** [comment]
This seems straightforward enough to implement. The only question is how it should interact with the current use of the quickfix list. Should it use both the quickfix list and tag stack, just the tag stack if `settagstack` is available, have an option to choose between them, etc?

**Comment by j-hui** [comment]
I'm not totally sure. As I imagined it, there would be a `g:coqtail_updatetagstack` setting that could be used to turn this feature on or off. But I'm not sure if that is compatible with the quickfix list feature (as far as I'm aware, it's not), or whether both should be used together.

How do you (or others) use the quickfix list?

**Comment by whonore** [comment]
Currently `coqtail#gotodef` generates a list of search patterns to locate the definition, then calls `:vimgrep` to find them and add them to the quickfix list (`coqtail#util#qflist_search`). Then it tries to jump to the first one with `:cfirst`. You can navigate forward and backwards through the list with `:cn` and `:cN` and you can also navigate between jumps in the jumplist with `<C-O>`, `<C-I>`, etc.

So it works pretty similarly to the tag stack, just with a different set of commands to navigate. It shouldn't be too hard to make `gotodef` modify the tag stack instead of/in addition to the quickfix list, but probably it makes sense to have an option to pick just one. While we're at it we could support the location list as an option too since it's just changing `:vimgrep` to `:lvimgrep` and `:cfirst` to `:lfirst`.
