### ISSUE TITLE
Is redraw necessary on panel refresh?

### ISSUE THREAD

**Issue by tomtomjhj** [whonore/Coqtail#221]
`coqtail#panels#refresh` runs `:redraw` at the end.
https://github.com/whonore/Coqtail/blob/358747255db85579498dfc6e03dcd808d5b81d34/autoload/coqtail/panels.vim#L324
This has various side effects such as flickering cursor (Vim) and disappearing IncSearch highlights (both Vim and NeoVim), which are quite annoying.
I have been using Coqtail for a few days with that line removed, and it seems to work well. 
So I think it makes sense to remove that line if there is no specific need for it (which I could not find from git history).

**Comment by whonore** [comment]
The origin of that `redraw` command seems to date back to the [first commit](https://github.com/whonore/Coqtail/blob/98d0169e079fcd4f9f1e04ea3d5a6b877a5cc215/autoload/coqtail.py#L300), which was copied from when I forked [Coquille](https://github.com/the-lambda-church/coquille/blob/df2460066686367b7949fe024c43ffd9d672f469/autoload/coquille.py#L316), so it very well may not be necessary. I would imagine that the worst removing it could do is to slightly delay updating the highlighting for the checked region, but there's already a bit of delay because of how the async code works so it should be fine. Maybe keep testing it a couple more days and I will too and if everything seems fine we can remove it.

**Comment by whonore** [comment]
I may have spoken too soon because I'm still seeing the error even with `redraw`, though much less frequently.
