### ISSUE TITLE
Error highlighting for failed sentences is distracting when editing

### ISSUE THREAD

**Issue by gullcomb** [whonore/Coqtail#250]
After evaluating a sentence fails, Coqtail highlights the erroneous part. That part is obviously a good feature. The issue is about subsequently editing the failed sentence: the highlighting stays at the exact same position until the next interaction with Coq which is quite distracting, especially with the default error highlighting.

This request is for a way to remove the highlighting, acknowledging the error, without forcing a Coq interaction. My current workaround is to undo the previous sentence, then redo it. That suggest the following behaviour (probably guarded by a `g:coqtail_` flag): when a sentence errors, the checked region *includes* the erroneous sentence, with error highlighting on top, and acknowledging the error is by undoing that sentence, removing both the error and checked region highlights. If that idea is too complicated to implement a dedicated mapping is fine.

**Comment by tomtomjhj** [comment]
Tip: If the cursor is in the failed sentence, `CoqToLine` (or corresponding mapping) will remove the error highlight without interacting with Coq. This works because `CoqToLine` checks up to the previous sentence, which is already checked. If the cursor is not on the failed sentence, you can use `CoqJumpToError` to jump to that sentence.

**Comment by gullcomb** [comment]
@tomtomjhj Nice trick! That's a solution that works for me, but I still feel that this should be documented somewhere. Especially because the default Error highlighting is nigh unreadable for me (am I the only one?) and Coqtail is the reason I customised it. I might write a pull request in a short while, but feel free to go ahead.

**Comment by whonore** [comment]
Thanks for reporting this. I agree that @tomtomjhj's suggestion is probably the easiest way of clearing the error highlighting. I'd be happy to accept improvements to the documentation about this point, but I'll be out of town for the next two weeks and won't be able to review any PRs until I return.

Also, the Coqtail error highlighting can be controlled by the `CoqtailError` syntax group if you'd prefer not to change the default `Error` group. The Syntax Highlighting and Indentation section of the README has more information about customizing the Coqtail syntax highlighting.

**Comment by gullcomb** [comment]
I have a pull request ready but there is one minor wrinkle I want to discuss here: the proposed solution has the side-effect of clearing the `Info` buffer. I can usually recover that content easily but it would be extra nice if I did not have to.

**Comment by whonore** [comment]
So I can think of a couple options:

1. Change `CoqToLine` so it doesn't clear the Info panel if no new sentences are  checked or rewound.
2. Same as 1 but put this behavior behind an option.
3. Create a new command (e.g., `CoqClearError`) that just clears the `CoqError` highlighting. We could also have an option to automatically call this command if anything inside the error region is edited (using `autocmd`s such as `TextChanged` or something similar).

My preference is for option 3 since it addresses your concern more directly whereas 1 and 2 are just taking advantage of a side of effect of `CoqToLine`.

**Comment by gullcomb** [comment]
I am not sure if that behaviour is intended, but I just noticed that rewinding one sentence or more using `CoqToLine` already has option 1 behaviour: it clears the error highlighting but does not clear the `Info` buffer. So I guess one could see options 1 and 2 as extending that behaviour to zero sentences.

**Comment by whonore** [comment]
That's a good point, maybe for consistency it would be best to treat `CoqToLine` on the current line as rewinding 0 steps. That should be a pretty simple change so I'll try to make it today and then you can remove the caveat about the Info panel from #259. I also still like option 3 as a solution so I may implement that soon too.
