### ISSUE TITLE
Universe level different

### ISSUE THREAD

**Issue by ju-sh** [whonore/Coqtail#251]
When we try

```
Set Printing Universes.
Check Type.
```

for the first time after starting coq with coqtail, I get output as

```
Type@{filename.3}
     : Type@{filename.3+1}
(* {filename.3} |=  *)
```

I was wondering why the universe level (that's what it's called, right?) starts from 3 instead of 1 (or zero).

But on running it with coqc, we get

```
Type@{filename.1}
     : Type@{filename.1+1}
(* {filename.1} |=  *)
```

and the universe level starts from `1` itself.

Any idea why the level is starting from `3` when used with coqtail?

(I guess this is not a bug or anything, but I was just wondering why it was happening.)

 - Coq 8.12.2
 - Coqtail from master branch on Mon Jan 3 09:41:53 2022 -0600

**Comment by whonore** [comment]
The short answer is Coqtail does some bookkeeping stuff in the background that `coqc` doesn't. 

In particular it executes a no-op (`XMLInterfaceBase.noop`) for option and query commands (`Set`, `Check`, etc) because otherwise things can get weird when you rewind them (see #54). The no-op I initially chose was `Eval lazy in forall x, x`, which generates a new universe level for `x`'s implicit `Type` type annotation. It also depends on the context if `Implicit Type` is used, hence #252 and #253. #253 also fixes this inconsistency you pointed out because it no longer references `Type` at all.
