### ISSUE TITLE
Problematic handling of startup warning messages

### ISSUE THREAD

**Issue by Tantalus13A98B5F** [whonore/Coqtail#273]
Recently ran into something very similar to #225 with the latest branch. Though it has been fixed, I think there is a tiny little problem in the regexp, 

https://github.com/whonore/Coqtail/blob/f88e1b425d96b331a5375d6e35c741abdedc858d/python/xmlInterface.py#L53

There should be no whitespace after `Warning:`. Removing that fixed my problem locally.

**Comment by whonore** [comment]
Although I don't see any problem with removing the space from the regex, I haven't seen a case yet where keeping it breaks anything either. Do you have an easy way I can try to reproduce your problem?

**Comment by Tantalus13A98B5F** [comment]
[Invitation](https://github.com/Tantalus13A98B5F/coq-hw4) sent.

Not sure how to trigger other warnings so just sent my original repo... Many thanks if you are okay with it!

**Comment by whonore** [comment]
Thanks, it looks like the problem is when the warning message is long enough (e.g., because of a long file path that doesn't exist) it wraps to the next line so there's a newline instead of a space after `Warning:`. Your suggestion of just removing the space from the regex should be all that's needed.
