### ISSUE TITLE
Feature Request: option to omit proofs when scripting (auto-admit)

### ISSUE THREAD

**Issue by lgaeher** [whonore/Coqtail#320]
It would be great to have an option to advance the buffer while automatically admitting the proofs for faster processing, similar to PG (https://proofgeneral.github.io/doc/master/userman/Coq-Proof-General/#Omitting-proofs-for-speed).
One way the interface for this could work is to have a variant of `<leader>cl` that skips proofs.

**Comment by whonore** [comment]
Thanks, that sounds like a useful feature. It's sort of a poor man's asynchronous proof checking. I agree it would make sense to expose this through a command like `CoqToLineAdmit`, or maybe an option to `CoqToLine`. I'm leaning towards not defining a mapping by default because there are already so many and I can't think of an obvious mnemonic, but it should be easy and well documented for people to define their own.

A couple subtleties I can think of:
- Same caveats as Proof General (no nested proofs, must be bracketed by `Proof` and `Qed`/`Admitted`/`Defined`).
- Have to avoid matching comments/strings (`(* Proof. *) Definition x := 1. (* Qed. *)` shouldn't be omitted).
- Need to preserve line/column numbers for error locations to make sense. One easy option is to replace everything between `Proof` and `Qed` with whitespace.
- The skipped-over proofs should be marked somehow (e.g., highlight `Qed` like `Admitted`).
