### ISSUE TITLE
Error on some large operations

### ISSUE THREAD

**Issue by bn-peters** [whonore/Coqtail#351]
Some operations with particularly large outputs currently cause an error:

```
Error detected while processing function <SNR>68_chanrecv[30]..function <SNR>68_chanrecv:
line    9:
E1510: Value too large:
Press ENTER or type command to continue
```

Two simple examples that cause this:
```
Search Prop.

Lemma t (a b c d e f g h i j k : bool) : True.
Proof.
  destruct a, b, c, d, e, f, g, h, i, j, k.
Abort.
```

This issue might have also locked up my CoqTail (and, by extension, my Vim) instance; although I am not able to reproduce that.

**Comment by whonore** [comment]
What version of vim/neovim are you using? I'm not able to reproduce that error with your examples on vim 9.0.2190, 9.1.346 or neovim 0.9.5.

**Comment by bn-peters** [comment]
Good point, I probably should have investigated this further... I can reproduce this with the current Neovim master on MacOS; more specifically [this commit](https://github.com/neovim/neovim/commit/e1ca7a7bfc954fae6991fc86d5da1a4eda864903). 

```
$ nvim --version
NVIM v0.10.0-dev-2947+ge1ca7a7bf
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188
Run "nvim -V1 -v" for more info
```

Also, a perhaps more direct way to reproduce:
```
Goal True.
Proof.
  do 4000 idtac "Hello World".
Abort.
```

**Comment by whonore** [comment]
Weird, I'm still not hitting that error with that commit of neovim on MacOS, but thanks to your debugging I think I know what's going on. The first error (`E474: Expected string end`) is expected. `s:chanrecv` might only have a partial response so it just tries `json_decode`, catches the error, and tries again when it gets more data. But it looks like in your case, the partial response is long enough that neovim blows up when it tries to format the error message.

I think I can fix this by actually checking if we have a complete response instead of just blindly trying to decode it. It looks like there should always be an empty string after a complete line so that should be pretty easy to check and I'm not sure why I wasn't doing it to begin with. The only issue would be if neovim also blows up parsing a really long valid JSON string.
