### ISSUE TITLE
case where coqtail is ~1s slower per action than PG

### ISSUE THREAD

**Issue by andres-erbsen-sifive** [whonore/Coqtail#55]
https://github.com/sifive/Kami/blob/bf1564ecd875872aa465f14e97bf6f52825f82e1/Tutorial/SPI.v#L414

**Comment by whonore** [comment]
CoqIDE also seems to be very slow there.

**Comment by whonore** [comment]
Looking at the debugging logs it seems like it could be because there are a lot of shelved and admitted goals that have fairly large proof contexts so the XML response to the `Goal` query is pretty large. Not sure why PG wouldn't be affected by this though. The following example displays a similar slowdown.
```
Goal True.
  do 1000 (assert True by admit); clear.
  idtac.
Abort.

**Comment by JasonGross** [comment]
PG is unaffected because coqtop itself is responsible for pruning the context of shelved goals; only the context of the currently focused goal is serialized in `-emacs` mode (which is what PG uses; the version of PG which uses the xml protocol is not sufficiently stable for wide-spread use).

**Comment by whonore** [comment]
This should finally be solvable now with coq/coq#15623.
